[package]
name             = "omni-node"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "omni-node"
path = "src/main.rs"

[dependencies]
omni-types         = { workspace = true }
omni-net           = { workspace = true }
omni-store         = { workspace = true }
tokio              = { workspace = true }
clap               = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow             = { workspace = true }
serde_json         = { workspace = true }
